# Copyright (c) 2015 Giovani Ferreira Silvério da Silva.

# Scrypt implementation
# Using the 'scrypt' gem
require 'scrypt'

class ScryptHash

	# The hash generated by the gem
	attr_accessor :hash

	# Can be initialized with any text
	def initialize password
		# Check if the text is a valid scrypt hash
		begin
			# Using an auxiliar var for avoid problems writting on @hash in rescue case
			aux = SCrypt::Password.new(password)
			@hash = aux
		rescue
			# If fails, generate a new scrypt hash
			@hash = SCrypt::Password.create(password)
		end
	end

	# Compares a given text to a scrypt hash
	def ==(toCompare)
		return @hash == toCompare
	end

	# Return all informations needed from hash
	def prepareForSave
		return {:algorithm => "scrypt", :secret => @hash}
	end

end
